### ISSUE TITLE
Bump requests to 2.28.2 for HA Release 2023.3.1

### ISSUE THREAD

**Issue by antibill51** [hekmon/rtetempo#11]
Hi ! 
With HA Release 2023.3.1, 
rtetempo does'nt start.

manifest file want "requests==2.28.1",
HA switch to 2.28.2

Errors on logs : 
Unable to install package requests==2.28.1: ERROR: Cannot install requests==2.28.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

Setup failed for custom integration rtetempo: Requirements for rtetempo not found: ['requests==2.28.1'].

**Comment by dudu7731** [comment]
hi,

meanwhile edit /root/config/custom_components/rtetempo/manifest.json and change line  : 
"requests==2.28.1"
to
"requests==2.28.2"

I think that putting a >= might work too instead of == for less further changes

**Comment by hekmon** [comment]
Just saw it too. I will check it this morning 👍

**Comment by hekmon** [comment]
Fixed with [v1.3.1](https://github.com/hekmon/rtetempo/releases/tag/v1.3.1).

I [simplified](https://github.com/hekmon/rtetempo/blob/v1.3.1/custom_components/rtetempo/manifest.json#L10) the dependencies requirements in order to be more resilient for future upgrade.

The others dependencies were indirect, the only real important is `requests-oauthlib`:
* Switch this one with a `>=`
* Removed the other 2 as they are deps of the first one (and declared as such within)

Thank you for your reactivity and inputs !
