### ISSUE TITLE
Next Day - Morning not shown as "undetermined"

### ISSUE THREAD

**Issue by lsd87** [hekmon/rtetempo#2]
At 6:00am - RTE Tempo Porchaine couleur goes to "Unavailable", at 6:14am it changed to "Blanc"
Should it not stay as "Unavailable" unit around 10:40am or when RTE decides what next day tariff will be

![Tempo-Prochaine Couleur](https://user-images.githubusercontent.com/17533711/216009823-edffca3f-0001-447c-a9a9-759018889ca4.png)

**Comment by hekmon** [comment]
Indeed the official hour announced by RTE is (around) 10h40.

But during my tests I realised RTE actually publish the new color far sooner than that on their API ! The color announced has always been around 6h~6h30 since I started this project and it never changed afterward.

I am not "making up" the next color, if next day color change to unavailable to Bleu/Blanc/Rouge it is because their own API is telling that this will be the next day color, even tho it is still very early in the morning.

This one of the reason I wanted to use the RTE API and not the EDF API : this is the best place to have the information sooner than anywhere else :)

**Comment by lsd87** [comment]
Thanks for the quick reply, - as long as it works great - I was going with what the RTE web site stated (10:40)
I want to run 2 RGB lights showing today and tomorrows colours so it's easy to see which days (RED) not to use any high powered devices
Thanks for making this Intergration available :-)

**Comment by hekmon** [comment]
> Thanks for the quick reply, - as long as it works great - I was going with what the RTE web site stated (10:40)

I was the first surprised ! Even their API documentation instructs developers to come and check at 10h40. I was doing that in the beginning, but the next day color was always there, so I moved my timer sooner and sonner to finally catch the time where it was not yet published. I did not expect to go that far in the morning but hey, I am not complaining to have the information before anyone else :D

> I want to run 2 RGB lights showing today and tomorrows colours so it's easy to see which days (RED) not to use any high powered devices

My next project too ! Hopefully with an ESP32 and ESPHome...

> Thanks for making this Intergration available :-)

I needed it for myself, but I am glad it is useful to others :)

**Comment by lsd87** [comment]
I've just got 2 RGB Zigbee light bulbs from LIDL (8€) each, so under home assistant automations will just set the colour.
Just need to make up a box (3DPrint) to put them in.

Going to try your lixeeticdin next and see if it works with a Micro Teleinfo
[https://www.tindie.com/products/hallard/micro-teleinfo-v20/](url)
Also have the Wemos ESP shield
[https://www.tindie.com/products/hallard/wemos-teleinfo/](url)
[https://github.com/hallard/WeMos-TIC](url)
Want to try and do a running costs per day/week/month/year and display on home assistant + grafana (loads of work)

**Comment by hekmon** [comment]
Nice ! You have your hands full with all that work ^^

If you try the lixeeticdin integration, be sure to directly try the v2 beta, a lot have change (for the better). The integration itself will change name to linkytic once the v2 is released (which should be soon everything is stable except for the triphase support that I need more user test feedback but I since it enhance a lot for single phase user too I don't want to hold on too long on the v2 release).

**Comment by hekmon** [comment]
Your issue motivated me to release the v2 of https://github.com/hekmon/linkytic

Enjoy !
