### ISSUE TITLE
Switch price per hour sensor example to be €/kWh

### ISSUE THREAD

**Issue by fcrozat** [hekmon/rtetempo#8]
Currently, the example given for price per hour sensor is not in euro cents, not euro, which make it not usable on the Energy dashboard as price source.

I would suggest to drop the * 100 in the template yaml to have the proper price in €

**Comment by hekmon** [comment]
Yes the example does show the price in cents because it is intended to be showed/printed on screen as a widget and not used as a source for the energy dashboard.

Switching it to euros would result in the loss of the visual sub cents values. On the other end, [source prices](https://gist.github.com/hekmon/33cba41728bfe2e4e522851da052f91f) used in the example are in € especially because their are design to be used as input in the energy dashboard.

I know a lot of people are seeking to have a dynamic prices sensor to be applied to their single metering sensor ([here](https://github.com/hekmon/rtetempo/issues/3#issuecomment-1414331855) and [here](https://community.home-assistant.io/t/get-edf-tempo-information/145003/79?u=hekmon)). But using tempo I personnaly think this is a not-so-good approach: the only SoT (source of truth) of how many kWh you have consumed in each color and on/off peak are the Linky integrated counters. They are the one retreived by Enedis and transmitted to EDF for billing. They are the ones people should recover to applied (fixed) prices on each of them. Having a single global metering device and trying to apply on it and constantly changing price is an approximation at best.

Not even mentionning that you will lost this kind of details from HA:
![image](https://user-images.githubusercontent.com/3418467/219902069-62f36ce4-9fdb-4727-9371-ec74e0fa7763.png)

This is why, for this example, everything related to prices (input numbers and template sensor) are in seperated github gists: they are not part of this integration. This integration is all about Tempo colors from RTE. And RTE has nothing to do with prices (EDF does). This example is here to show on someone can use its sensors to make something more. But I am fairly confident that if someone does need a dynamic prices sensor, it will be easy for him to adapt my example.

But I do not want to publish it like this because I do not "believe" this is the right way of doing it :)

**Comment by fcrozat** [comment]
Wow, I wasn't aware you could get this kind of refinement in HA Energy dashboard. I've read the dicusssion on HA Community (quite interesting). Do you have a gist with your sensor template for Linky ?

**Comment by hekmon** [comment]
They actually are not template sensors, but real sensors from my other integration [LinkyTIC](https://github.com/hekmon/linkytic). I use the prices in the input numbers from the example for each of them in order to have this energy dashboard results.

**Comment by fcrozat** [comment]
Ok. I'll check the other solution mentioned on the forum. Thanks
